name: coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: checkout@v2
        with:
          fetch-depth: ‘2’
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage report -m
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: 8bff81623296491d8ff36a39112e841f
